### ISSUE TITLE
Dynmap-PreciousStones dosn't work

### ISSUE THREAD

**Issue by deevee1982** [marcelo-mason/Dynmap-PreciousStones#2]
[11:25:59 INFO]: This server is running CraftBukkit version git-Spigot-550ebac-7019900 (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)

PrecisiusStone: 10.0.3
Dynmap-PrecisiusStone: dev 14

[11:19:58] [Server thread/ERROR]: Could not load 'plugins/Dynmap-PreciousStones.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:154) ~[spigot.jar:git-Spigot-550ebac-7019900]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot.jar:git-Spigot-550ebac-7019900]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugins(CraftServer.java:291) [spigot.jar:git-Spigot-550ebac-7019900]
        at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:152) [spigot.jar:git-Spigot-550ebac-7019900]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:505) [spigot.jar:git-Spigot-550ebac-7019900]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
        ... 6 more

**Comment by RoboMWM** [comment]
Yea... looks like he didn't even bother to test this. In the meantime, here's a properly updated one, in case anyone else has come across this: https://github.com/Dandielo/Dynmap-PreciousStones
